name: vue-compositions-publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: thonatos/github-actions-nodejs

    steps:
      - name: Checkout
        uses: actions/checkout@master

      # 依赖安装
      - name: Install Dependencies
        run: npm install
        
      # NPM 包发布
      - name: Release NPM Package
        run: npm run publish2
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
